// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pilot.DAL;

#nullable disable

namespace Pilot.Migrations
{
    [DbContext(typeof(PilotDbContext))]
    partial class PilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pilot.Models.Poi", b =>
                {
                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.ToTable("POI", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
